export const API_URL = 'https://api.unsplash.com';
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token?';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize?';
export const ACCESS_KEY = 'jMZbk9pKKmuRE66dzhCRn9Mi57CNSA9wy-34gMwn5_g';
// 'KTIHbdQSpYUJBsKhBHfTKGcJlDefxvZS_HHVGh8OCNo';
// 'jMZbk9pKKmuRE66dzhCRn9Mi57CNSA9wy-34gMwn5_g';
export const SECRET_KEY = 'vnmXQmvSeCBCiz9TUmFhpehq4esQqOEZTCKM6LcSC7A';
// 'By1gbxGVgf5phBzGInXR_OeK3A5KaqO9wB0XzNKm5NA';
// 'vnmXQmvSeCBCiz9TUmFhpehq4esQqOEZTCKM6LcSC7A';
export const RESPONSE_TYPE = 'code';
export const REDIRECT_URI = 'https://gallery-rose-seven.vercel.app/auth';
export const SCOPE = 'public read_user read_photos write_likes';
export const GRANT_TYPE = 'authorization_code';
